title: Blockchain (and related) Naming Systems
email: nweaver@gmail.com
description: Report on Blockchain Naming Systems

theme: minima
lsi: false
safe: true
source: /pages
destination: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
